import React, { useEffect, useMemo, useRef, useState } from 'react';
import { notes as notesApi, type KnowledgeHistory, type TimelineItem } from '../services/apiClient';
import { filterTimeline, timelineBuckets, timelineExport, timelineLanes, type TimelineFilters, type TimelineView } from './knowledgeTimelineModel';
import { localDay } from './knowledgeExplorerModel';
import { RELATION_LABELS } from './relationColors';
import RemixIcon from './RemixIcon';
import ConstructionSequence from './ConstructionSequence';
import '../styles/knowledgeTimeline.css';
interface Props {spaceId:string; currentUserId?:string; lang:'zh'|'en'; initialNoteId?:string|null; onLocateNote?:(id:string,spaceId?:string)=>void; onShowNetwork?:(id:string,spaceId?:string)=>void; onClose:()=>void;}
const icons={note:'sticky-note-line',build_on:'git-branch-line',revision:'edit-2-line',ai_feedback:'feedback-line',ai_chat:'chat-3-line'};
function Picker({label,options,value,onChange}:{label:string;options:{id:string;label:string}[];value:string[];onChange:(ids:string[])=>void}) {
 return <details className="timeline-picker"><summary>{label}{value.length>0&&<b>{value.length}</b>}<RemixIcon name="arrow-down-s-line" size={14}/></summary><div className="timeline-picker-panel">{options.length?options.map(o=><label key={o.id}><input type="checkbox" checked={value.includes(o.id)} onChange={e=>onChange(e.target.checked?[...value,o.id]:value.filter(id=>id!==o.id))}/><span>{o.label}</span></label>):<span>—</span>}</div></details>;
}
export default function SpaceTimeline({spaceId,lang,initialNoteId,onLocateNote,onShowNetwork,onClose}:Props) {
 const zh=lang==='zh';const [scope,setScope]=useState<'course'|'space'>('course');
 const [history,setHistory]=useState<KnowledgeHistory|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const [view,setView]=useState<TimelineView>('overall'),[filters,setFilters]=useState<TimelineFilters>({includeTeachers:true,includeAi:true,notes:initialNoteId?[initialNoteId]:[]});
 const [presentation,setPresentation]=useState<'sequence'|'records'>('sequence');
 const [selected,setSelected]=useState<TimelineItem|null>(null),[selectedEvents,setSelectedEvents]=useState<TimelineItem[]>([]),[anonymous,setAnonymous]=useState(false),[empty,setEmpty]=useState(false),[shown,setShown]=useState(150),[rowsShown,setRowsShown]=useState(40);
 const dialog=useRef<HTMLDivElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.querySelector<HTMLButtonElement>('[data-timeline-close]')?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current();}if(e.key==='Tab'){const targets=[...(dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input,select,summary,[tabindex="0"]')??[])].filter(el=>el.getClientRects().length);const first=targets[0],last=targets.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');setHistory(null);setSelected(null);setSelectedEvents([]);notesApi.timeline(spaceId,scope).then(data=>{if(!cancelled)setHistory(data);}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Could not load timeline');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[spaceId,scope,retry]);
 const patch=(part:Partial<TimelineFilters>)=>setFilters(f=>({...f,...part}));
 const events=useMemo(()=>history?filterTimeline(history,filters):[],[history,filters]);
 const buckets=useMemo(()=>timelineBuckets(events),[events]);
 const people=history?.context?.participants??[];const personById=useMemo(()=>new Map(people.map(p=>[p.id,p])),[people]);
 const displayPerson=(id:string|null|undefined,name?:string|null)=>id?(anonymous?(personById.get(id)?.code??(zh?'成员':'Member')):(personById.get(id)?.name||name||(zh?'成员':'Member'))):(zh?'未记录':'Not recorded');
 const byNote=useMemo(()=>new Map(history?.structure?.notes.map(n=>[n.id,n])),[history]);
 const labels:Record<TimelineItem['kind'],string>=zh?{note:'贡献',build_on:'Build-on',revision:'修订',ai_feedback:'我的 AI 反馈',ai_chat:'我的 AI 对话'}:{note:'Contribution',build_on:'Build-on',revision:'Revision',ai_feedback:'My AI feedback',ai_chat:'My AI chat'};
 const label=(e:TimelineItem)=>e.kind==='note'&&byNote.get(e.noteId??'')?.type==='riseabove'?(zh?'综合观点':'Rise-above'):labels[e.kind];
 const date=(iso:string)=>new Date(iso).toLocaleDateString(zh?'zh-CN':'en-GB',{month:'short',day:'numeric'});
 const fullDate=(iso:string)=>new Date(iso).toLocaleString(zh?'zh-CN':'en-GB');
 const lanes=useMemo(()=>{
  if(!history||view==='overall')return [];
  const rows=timelineLanes(events,history,view,Boolean(filters.received),empty&&view==='people');
  const groupMembers=new Set(history.context?.groups.filter(g=>filters.groups?.includes(g.id)).flatMap(g=>g.memberIds));
  return rows.filter(r=>view!=='people'||(!filters.excluded?.includes(r.id)&&(!filters.people?.length||filters.people.includes(r.id))&&(!filters.groups?.length||groupMembers.has(r.id)||r.events.length>0)&&(filters.includeTeachers!==false||personById.get(r.id)?.role!=='teacher')));
 },[history,events,view,filters,empty,personById]);
 const days=useMemo(()=>{const map=new Map<string,TimelineItem[]>();for(const e of events.slice(0,shown)){const day=localDay(e.at);const list=map.get(day)??[];list.push(e);map.set(day,list);}return [...map];},[events,shown]);
 const activity=useMemo(()=>buckets.map(b=>({ ...b,events:events.filter(e=>{const d=localDay(e.at);return d>=b.key&&d<=b.end;})})),[events,buckets]);
 useEffect(()=>{setShown(150);setRowsShown(40);setSelected(null);setSelectedEvents([]);},[filters,scope]);
 const reset=()=>{setFilters({includeTeachers:true,includeAi:true});setEmpty(false);};
 const download=(filename:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const exportRows=()=>{if(!history)return;const result=timelineExport(history,events,filters,view);download('hakcc-timeline-events.csv',result.csv,'text/csv;charset=utf-8');download('hakcc-timeline-manifest.json',JSON.stringify(result.manifest,null,2),'application/json');};
 const pick=(list:TimelineItem[])=>{setSelectedEvents(list);setSelected(list[0]??null);};
 const options=people.map(p=>({id:p.id,label:anonymous?p.code:p.name||p.code}));
 const eventCard=(e:TimelineItem)=><button key={e.id} className={`timeline-record ${selected?.id===e.id?'is-selected':''}`} onClick={()=>pick([e])}><span className={`timeline-record-icon kind-${e.kind}`}><RemixIcon name={icons[e.kind]} size={17}/></span><span className="timeline-record-copy"><span className="timeline-record-meta">{e.aiGenerated?'AI partner':displayPerson(e.actorId,e.actorName)}<b>{label(e)}</b><time>{new Date(e.at).toLocaleTimeString(zh?'zh-CN':'en-GB',{hour:'2-digit',minute:'2-digit'})}</time></span><strong>{e.noteTitle||(zh?'未命名 Note':'Untitled Note')}</strong>{e.kind==='build_on'&&<span>{RELATION_LABELS[lang][e.relationType??'extend']??e.relationType} · {zh?'基于':'Built on'} {e.targetNoteTitle}</span>}<small>{e.spaceTitle|| (zh?'当前空间':'Current space')}</small></span><RemixIcon name="arrow-right-s-line" size={16}/></button>;
 return <div className="workspace-view-shell knowledge-explorer-shell" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={dialog} className="knowledge-explorer construction-timeline" role="dialog" aria-modal="true" aria-label={zh?'构建时间线':'Construction timeline'}>
  <header className="knowledge-header"><div className="knowledge-heading"><span className="knowledge-heading-icon"><RemixIcon name="history-line" size={23}/></span><div><div className="knowledge-eyebrow">{zh?'共同构建的过程':'THE CONSTRUCTION PROCESS'}</div><h2>{zh?'构建时间线':'Construction timeline'}</h2></div></div><div className="knowledge-mode-switch" role="group" aria-label={zh?'时间线视角':'Timeline perspective'}>{(['overall','notes','people'] as const).map((v,i)=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{(zh?['整体轨迹','Note 轨迹','成员轨迹']:['Overview','Note tracks','People tracks'])[i]}</button>)}</div><button className="knowledge-close" disabled={loading} aria-label={zh?'刷新时间线':'Refresh timeline'} title={history?.generatedAt?`${zh?'记录读取于':'Loaded at'} ${fullDate(history.generatedAt)}`:undefined} onClick={()=>setRetry(n=>n+1)}><RemixIcon name="refresh-line" size={19}/></button><button data-timeline-close className="knowledge-close" aria-label={zh?'关闭':'Close'} onClick={onClose}><RemixIcon name="close-line" size={21}/></button></header>
  <div className="knowledge-subheader"><p>{zh?'回看贡献、接续与修订，观察共同构建如何展开。':'Follow contributions, Build-ons and revisions through the shared inquiry.'}</p><div className="knowledge-summary"><span><b>{events.length}</b>{zh?'记录':'events'}</span><span><b>{new Set(events.flatMap(e=>[e.noteId,e.targetNoteId]).filter(Boolean)).size}</b>Note</span><span><b>{new Set(events.map(e=>e.actorId).filter(Boolean)).size}</b>{zh?'行动者':'actors'}</span></div></div>
  <div className="timeline-filters"><label className="knowledge-search"><RemixIcon name="search-line" size={16}/><input aria-label={zh?'搜索时间线':'Search timeline'} value={filters.query??''} placeholder={zh?'搜索观点或内容':'Search ideas or content'} onChange={e=>patch({query:e.target.value})}/></label><select aria-label={zh?'时间线范围':'Timeline scope'} value={scope} onChange={e=>{setScope(e.target.value as typeof scope);patch({spaces:[]});}}><option value="course">{zh?'全班 · 可见空间':'Class · accessible spaces'}</option><option value="space">{zh?'当前知识空间':'Current space'}</option></select>
   <Picker label={zh?'小组':'Groups'} options={(history?.context?.groups??[]).map(g=>({id:g.id,label:g.name}))} value={filters.groups??[]} onChange={ids=>patch({groups:ids})}/><Picker label={zh?'空间':'Spaces'} options={(history?.context?.spaces??[]).map(s=>({id:s.id,label:s.title}))} value={filters.spaces??[]} onChange={ids=>patch({spaces:ids})}/><Picker label={zh?'查看成员':'Include people'} options={options} value={filters.people??[]} onChange={ids=>patch({people:ids})}/><Picker label={zh?'排除成员':'Exclude people'} options={options} value={filters.excluded??[]} onChange={ids=>patch({excluded:ids})}/>
   <details className="timeline-picker"><summary>{zh?'更多筛选':'More filters'}<RemixIcon name="filter-3-line" size={14}/></summary><div className="timeline-picker-panel timeline-advanced"><label>{zh?'开始日期':'From'}<input type="date" value={filters.from??''} onChange={e=>patch({from:e.target.value})}/></label><label>{zh?'结束日期':'To'}<input type="date" value={filters.to??''} onChange={e=>patch({to:e.target.value})}/></label><label><input type="checkbox" checked={filters.includeTeachers!==false} onChange={e=>patch({includeTeachers:e.target.checked})}/>{zh?'包含教师相关记录':'Teacher-related records'}</label><label><input type="checkbox" checked={filters.includeAi!==false} onChange={e=>patch({includeAi:e.target.checked})}/>{zh?'包含 AI 生成 Note':'AI-generated Notes'}</label><label><input type="checkbox" checked={Boolean(filters.privateAi)} onChange={e=>patch({privateAi:e.target.checked,kinds:e.target.checked?filters.kinds:filters.kinds?.filter(k=>!k.startsWith('ai_'))})}/>{zh?'显示我的私人 AI 活动':'My private AI activity'}</label><label><input type="checkbox" checked={Boolean(filters.received)} onChange={e=>patch({received:e.target.checked})}/>{zh?'成员轨迹包含收到的 Build-on':'Include received Build-ons in people tracks'}</label><label><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>{zh?'显示暂无活动成员':'Show people without events'}</label><label><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/>{zh?'使用成员代号显示':'Use participant codes'}</label><fieldset><legend>{zh?'事件类型（不选则全部）':'Event types (empty = all)'}</legend>{Object.keys(labels).filter(k=>filters.privateAi||!k.startsWith('ai_')).map(k=><label key={k}><input type="checkbox" checked={filters.kinds?.includes(k)??false} onChange={e=>patch({kinds:e.target.checked?[...(filters.kinds??[]),k]:filters.kinds?.filter(kind=>kind!==k)})}/>{labels[k as TimelineItem['kind']]}</label>)}</fieldset></div></details>
   <button className="timeline-reset" onClick={reset}>{zh?'重置':'Reset'}</button>{history?.context?.canExport&&<button className="timeline-export" disabled={loading} onClick={exportRows}><RemixIcon name="download-2-line" size={15}/>{zh?'导出当前记录':'Export events'}</button>}
  </div>
  <div className="timeline-scope-note"><span>{history?.context?.spaces.length??0} {zh?'个可见空间':'accessible spaces'}{filters.groups?.length?` · ${zh?'按当前小组成员筛选':'Current group membership'}`:''}{filters.excluded?.length?` · ${zh?'已排除':'Excluded'} ${filters.excluded.length} ${zh?'位成员相关记录':'people’s related records'}`:''}</span><Picker label={zh?'选择 Note':'Select Notes'} options={(history?.structure?.notes??[]).map(n=>({id:n.id,label:n.title}))} value={filters.notes??[]} onChange={ids=>patch({notes:ids})}/></div>
  {loading&&<div className="knowledge-notice" role="status">{zh?'正在读取构建记录…':'Loading construction records…'}</div>}{error&&<div className="knowledge-notice is-error" role="alert">{error}<button onClick={()=>setRetry(n=>n+1)}>{zh?'重试':'Retry'}</button></div>}{history?.coverage?.truncated&&<div className="knowledge-notice">{zh?'数据超过读取范围，各来源展示最新 2,000 条；导出包含覆盖范围说明。':'Showing up to 2,000 recent rows per source; exports report this coverage boundary.'}</div>}
  <div className={`timeline-content ${selected?'has-detail':''}`}>
   <main className="timeline-stage">
    {view==='overall'&&<div className="timeline-presentation"><span>{zh?'构建轨迹':'CONSTRUCTION TRAJECTORY'}</span><div role="group" aria-label={zh?'整体轨迹呈现方式':'Overview presentation'}><button aria-pressed={presentation==='sequence'} onClick={()=>setPresentation('sequence')}><RemixIcon name="line-chart-line" size={15}/>{zh?'时间序列':'Time series'}</button><button aria-pressed={presentation==='records'} onClick={()=>setPresentation('records')}><RemixIcon name="list-check" size={15}/>{zh?'记录列表':'Event list'}</button></div></div>}
    {(view!=='overall'||presentation==='records')&&<><div className="timeline-activity" aria-label={zh?'构建活动时间分布':'Construction activity over time'}>{activity.map(b=><button key={b.key} title={`${b.key} – ${b.end}: ${b.events.length}`} onClick={()=>{if(b.events.length)pick(b.events);}} aria-label={`${date(b.key+'T12:00:00')}: ${b.events.length} ${zh?'条记录':'events'}`}><span className="timeline-activity-bar"><i style={{height:`${b.events.length?Math.max(12,b.events.length/Math.max(1,...activity.map(a=>a.events.length))*100):0}%`}}/></span><time>{date(b.key+'T12:00:00')}</time></button>)}</div>
    <div className="timeline-axis-note"><span>{buckets[0]?.grain==='week'?(zh?'每列一周':'Weekly columns'):buckets[0]?.grain==='month'?(zh?'每列一月':'Monthly columns'):(zh?'每列一天':'Daily columns')} · {view==='people'?(zh?'按实际行动者归组':'Grouped by the actual actor'):view==='notes'?(zh?'Build-on 会在相关的两条 Note 中出现':'Build-ons appear in both related Note tracks'):(zh?'按实际发生时间排列':'Ordered by recorded event time')}</span><span className="timeline-legend">{(['note','build_on','revision'] as const).map(k=><span key={k}><i className={`kind-${k}`}/>{labels[k]}</span>)}</span></div></>}
    <div className="timeline-stage-scroll" data-construction-scroll>
     {!events.length&&!loading&&<div className="knowledge-empty"><RemixIcon name="history-line" size={30}/><h3>{zh?'当前范围没有构建记录':'No records in this scope'}</h3><p>{zh?'调整筛选条件，或选择其他空间。':'Adjust the filters or choose another space.'}</p></div>}
     {view==='overall'&&presentation==='sequence'?<ConstructionSequence events={events} lang={lang} selectedId={selected?.id} actorName={e=>e.aiGenerated?'AI partner':displayPerson(e.actorId,e.actorName)} onPick={pick}/>:view==='overall'?<>{days.map(([day,list])=><section className="timeline-day" key={day}><h3><time>{new Date(day+'T12:00:00').toLocaleDateString(zh?'zh-CN':'en-GB',{year:'numeric',month:'long',day:'numeric'})}</time><span>{list.length} {zh?'条记录':'events'}</span></h3><div>{list.map(eventCard)}</div></section>)}{events.length>shown&&<button className="knowledge-load-more" onClick={()=>setShown(n=>n+150)}>{zh?'加载更多记录':'Load more events'}</button>}</>:<div className="timeline-matrix" style={{'--timeline-columns':buckets.length} as React.CSSProperties}><div className="timeline-matrix-head"><strong>{view==='notes'?'Note':(zh?'成员':'Participant')}</strong>{buckets.map(b=><time key={b.key} title={`${b.key} – ${b.end}`}>{date(b.key+'T12:00:00')}</time>)}</div>{lanes.slice(0,rowsShown).map(row=><div key={row.id} className="timeline-matrix-row"><div className="timeline-lane-label"><strong>{view==='people'&&anonymous?row.code:row.label}</strong><small>{row.events.length} {zh?'条记录':'events'}</small></div>{buckets.map(b=>{const cell=row.events.filter(e=>{const d=localDay(e.at);return d>=b.key&&d<=b.end;});return <div className="timeline-matrix-cell" key={b.key}>{cell.length>0&&<button className={cell.some(e=>e.id===selected?.id)?'is-selected':''} onClick={()=>pick(cell)} aria-label={`${row.label} · ${b.key} · ${cell.length} ${zh?'条记录':'events'}`}><span className="timeline-cell-types">{[...new Set(cell.map(e=>e.kind))].map(k=><i key={k} className={`kind-${k}`} title={labels[k]}/>)}</span><b>{cell.length}</b></button>}</div>;})}</div>)}{lanes.length>rowsShown&&<button className="knowledge-load-more" onClick={()=>setRowsShown(n=>n+40)}>{zh?'加载更多轨迹':'Load more tracks'}</button>}</div>}
    </div>
   </main>
   {selected&&<aside className="timeline-detail" aria-label={zh?'构建记录详情':'Construction event details'}><div className="knowledge-inspector-header"><span>{zh?'记录详情':'EVENT DETAILS'}</span><button aria-label={zh?'关闭记录详情':'Close event details'} onClick={()=>{setSelected(null);setSelectedEvents([]);}}><RemixIcon name="close-line" size={18}/></button></div>{selectedEvents.length>1&&<div className="timeline-selected-events">{selectedEvents.map(e=><button key={e.id} aria-pressed={selected.id===e.id} onClick={()=>setSelected(e)}>{label(e)} · {e.noteTitle}</button>)}</div>}<span className={`timeline-detail-kind kind-${selected.kind}`}>{label(selected)}</span><h3>{selected.noteTitle}</h3><p>{displayPerson(selected.actorId,selected.actorName)} · {fullDate(selected.at)}</p><small>{selected.spaceTitle}</small>{selected.kind==='build_on'&&<div className="timeline-related">{RELATION_LABELS[lang][selected.relationType??'extend']} · {zh?'基于':'Built on'} {selected.targetNoteTitle}</div>}{selected.kind==='revision'&&selected.snapshotComplete!==false?<div className="timeline-revision"><section><small>{zh?'修改前摘要':'Before excerpt'}</small><p>{selected.beforeExcerpt||(zh?'正文为空':'Empty content')}</p></section><section><small>{zh?'修改后摘要':'After excerpt'}</small><p>{selected.excerpt||(zh?'正文为空':'Empty content')}</p></section></div>:<p className="timeline-detail-excerpt">{selected.excerpt}</p>}{selected.snapshotComplete===false&&<p>{zh?'历史快照不完整，无法还原完整修订对照。':'Incomplete snapshots prevent a full revision comparison.'}</p>}{selected.excerptScope==='current'&&<small>{zh?'显示当前内容摘要':'Showing the current content excerpt'}</small>}<div className="timeline-detail-actions">{selected.noteId&&onLocateNote&&<button onClick={()=>onLocateNote(selected.noteId!,selected.spaceId??undefined)}>{zh?'打开原 Note':'Open original Note'}<RemixIcon name="arrow-right-up-line" size={15}/></button>}{selected.noteId&&onShowNetwork&&<button onClick={()=>onShowNetwork(selected.noteId!,selected.spaceId??undefined)}>{zh?'在 Build-on 网络中查看':'View in Build-on network'}<RemixIcon name="git-branch-line" size={15}/></button>}</div></aside>}
  </div>
  <footer className="knowledge-footer"><span>{events.length} {zh?'条构建记录':'construction events'}</span><span>{history?.context?.membershipBasis==='current'?(zh?'小组归属依据当前名单':'Group membership reflects the current roster'):''}{history?.context?.canExport?(zh?' · 导出保留时间、代号及筛选条件':' · Exports preserve times, codes and filters'):''}</span></footer>
 </div></div>;
}
